=== AMWA-TV/bcp-003/raml/APIs/schemas/token_response.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Token Response",
  "description": "OAuth2 Response for the request of a Bearer Token",
  "type": "object",
  "properties": {
    "access_token": {
      "description": "Access Token to be used in accessing protected endpoints",
      "type": "string"
    },
    "expires_in": {
      "description": "The UTC time in which the Bearer Token will expire",
      "type": "integer"
    },
    "refresh_token": {
      "description": "Refresh Token to be used to obtain further Access Tokens",
      "type": "string"
    },
    "scope": {
      "description": "The scope of the Access Token",
      "type": "string"
    },
    "token_type": {
      "description": "The form of the Token",
      "type": "string"
    }
  },
  "required": ["access_token", "expires_in", "token_type"]
}

=== AMWA-TV/bcp-003/raml/examples/token_response_example.json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5ueW0iLCJleHAiOjE1NDg4Njc3NDksInNjb3BlIjoiaXMtMDQiLCJpc3MiOiJodHRwczovL29hdXRoLnJkLmJiYy5jby51ayIsImlhdCI6MTU0ODg2NzcxOSwieC1ubW9zLWFwaSI6eyJhY2Nlc3MiOiJyZWFkIiwibmFtZSI6ImlzLTA0In0sIm5iZiI6MTU0ODg2NzcxOSwiYXVkIjpbIklTLTA0IiwiUmVhZCIsIkFjY2VzcyJdfQ.KdWfqabvUXMsHcsQVOwdEyTw98BXkJx8yQ9TYSqSf2Of0n3vBtJGyy1UXH3qhnTYSpS200B8XMsK0Fm1lVuSL6ZEMkPB0nFyUXFXma5XPdZgULJcyDernoRneVbwjPL7hQYu74kbYu9ozLke55hzicA5TaB1VJTa7cMfuE5My_KV_rOMXLzhzotLjOs7fne1o9J4687cGfT04cC0WnehKnGG6A1Exi2-zOQYN9l4BWP-lzMimvPYQ-HeikoljkF31vT5-NJJuK7yMLKVAD2LD6XoET9CsX6zN6yXifHs6hx7VRYvbsrNJECoLnwGQYQXOhsopLw0MypI6oYxbmFo9g",
  "expires_in": 864000,
  "refresh_token": "2PLfDfqSy4SSP46jilviCyw8lXRNc1FTInUCO9uTEAN8jOrz",
  "scope": "is04",
  "token_type": "Bearer"
}
